{
 "title": "Cloudflare Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "domain", "query": "SELECT domain from logs;" }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  country_name,\n  count(country_name) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by country_name\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(timestamp) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  domain in ($domain)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(timestamp) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  status != 200 AND\n  domain in ($domain)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(distinct(clientIP))\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Worker Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(timestamp)\nFROM logs\nWHERE\n  timestamp > now() - interval 24 hour\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(status) as \"2xx\",\n  CASE \n        WHEN hour(timestamp) = 0 then '0'\n        WHEN hour(timestamp) = 1 then '1'\n        WHEN hour(timestamp) = 2 then '2'\n        WHEN hour(timestamp) = 3 then '3'\n        WHEN hour(timestamp) = 4 then '4'\n        WHEN hour(timestamp) = 5 then '5'\n        WHEN hour(timestamp) = 6 then '6'\n        WHEN hour(timestamp) = 7 then '7'\n        WHEN hour(timestamp) = 8 then '8'\n        WHEN hour(timestamp) = 9 then '9'\n        WHEN hour(timestamp) = 10 then '10'\n        WHEN hour(timestamp) = 11 then '11'\n        WHEN hour(timestamp) = 12 then '12'\n        WHEN hour(timestamp) = 13 then '13'\n        WHEN hour(timestamp) = 14 then '14'\n        WHEN hour(timestamp) = 15 then '15'\n        WHEN hour(timestamp) = 16 then '16'\n        WHEN hour(timestamp) = 17 then '17'\n        WHEN hour(timestamp) = 18 then '18'\n        WHEN hour(timestamp) = 19 then '19'\n        WHEN hour(timestamp) = 20 then '20'\n        WHEN hour(timestamp) = 21 then '21'\n        WHEN hour(timestamp) = 22 then '22'\n        WHEN hour(timestamp) = 23 then '23'\n    END AS intervals\nFROM logs\nWHERE\n  timestamp > now() - interval 24 hour and\n  domain in ($domain) and\n  status regexp '^[2]+'\nGROUP BY intervals\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(status) as \"3xx\",\n  CASE \n        WHEN hour(timestamp) = 0 then '0'\n        WHEN hour(timestamp) = 1 then '1'\n        WHEN hour(timestamp) = 2 then '2'\n        WHEN hour(timestamp) = 3 then '3'\n        WHEN hour(timestamp) = 4 then '4'\n        WHEN hour(timestamp) = 5 then '5'\n        WHEN hour(timestamp) = 6 then '6'\n        WHEN hour(timestamp) = 7 then '7'\n        WHEN hour(timestamp) = 8 then '8'\n        WHEN hour(timestamp) = 9 then '9'\n        WHEN hour(timestamp) = 10 then '10'\n        WHEN hour(timestamp) = 11 then '11'\n        WHEN hour(timestamp) = 12 then '12'\n        WHEN hour(timestamp) = 13 then '13'\n        WHEN hour(timestamp) = 14 then '14'\n        WHEN hour(timestamp) = 15 then '15'\n        WHEN hour(timestamp) = 16 then '16'\n        WHEN hour(timestamp) = 17 then '17'\n        WHEN hour(timestamp) = 18 then '18'\n        WHEN hour(timestamp) = 19 then '19'\n        WHEN hour(timestamp) = 20 then '20'\n        WHEN hour(timestamp) = 21 then '21'\n        WHEN hour(timestamp) = 22 then '22'\n        WHEN hour(timestamp) = 23 then '23'\n    END AS intervals\nFROM logs\nWHERE\n  timestamp > now() - interval 24 hour and\n  domain in ($domain) and\n  status regexp '^[3]+'\nGROUP BY intervals\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(status) as \"4xx\",\n  CASE \n        WHEN hour(timestamp) = 0 then '0'\n        WHEN hour(timestamp) = 1 then '1'\n        WHEN hour(timestamp) = 2 then '2'\n        WHEN hour(timestamp) = 3 then '3'\n        WHEN hour(timestamp) = 4 then '4'\n        WHEN hour(timestamp) = 5 then '5'\n        WHEN hour(timestamp) = 6 then '6'\n        WHEN hour(timestamp) = 7 then '7'\n        WHEN hour(timestamp) = 8 then '8'\n        WHEN hour(timestamp) = 9 then '9'\n        WHEN hour(timestamp) = 10 then '10'\n        WHEN hour(timestamp) = 11 then '11'\n        WHEN hour(timestamp) = 12 then '12'\n        WHEN hour(timestamp) = 13 then '13'\n        WHEN hour(timestamp) = 14 then '14'\n        WHEN hour(timestamp) = 15 then '15'\n        WHEN hour(timestamp) = 16 then '16'\n        WHEN hour(timestamp) = 17 then '17'\n        WHEN hour(timestamp) = 18 then '18'\n        WHEN hour(timestamp) = 19 then '19'\n        WHEN hour(timestamp) = 20 then '20'\n        WHEN hour(timestamp) = 21 then '21'\n        WHEN hour(timestamp) = 22 then '22'\n        WHEN hour(timestamp) = 23 then '23'\n    END AS intervals\nFROM logs\nWHERE\n  timestamp > now() - interval 24 hour and\n  domain in ($domain) and\n  status regexp '^[4]+'\nGROUP BY intervals\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(status) as \"5xx\",\n  CASE \n        WHEN hour(timestamp) = 0 then '0'\n        WHEN hour(timestamp) = 1 then '1'\n        WHEN hour(timestamp) = 2 then '2'\n        WHEN hour(timestamp) = 3 then '3'\n        WHEN hour(timestamp) = 4 then '4'\n        WHEN hour(timestamp) = 5 then '5'\n        WHEN hour(timestamp) = 6 then '6'\n        WHEN hour(timestamp) = 7 then '7'\n        WHEN hour(timestamp) = 8 then '8'\n        WHEN hour(timestamp) = 9 then '9'\n        WHEN hour(timestamp) = 10 then '10'\n        WHEN hour(timestamp) = 11 then '11'\n        WHEN hour(timestamp) = 12 then '12'\n        WHEN hour(timestamp) = 13 then '13'\n        WHEN hour(timestamp) = 14 then '14'\n        WHEN hour(timestamp) = 15 then '15'\n        WHEN hour(timestamp) = 16 then '16'\n        WHEN hour(timestamp) = 17 then '17'\n        WHEN hour(timestamp) = 18 then '18'\n        WHEN hour(timestamp) = 19 then '19'\n        WHEN hour(timestamp) = 20 then '20'\n        WHEN hour(timestamp) = 21 then '21'\n        WHEN hour(timestamp) = 22 then '22'\n        WHEN hour(timestamp) = 23 then '23'\n    END AS intervals\nFROM logs\nWHERE\n  timestamp > now() - interval 24 hour and\n  domain in ($domain) and\n  status regexp '^[5]+'\nGROUP BY intervals\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Top Sites",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  path,\n  domain,\n  count(path) AS \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\nGROUP by path"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  user_agent,\n  count(user_agent) as count\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by user_agent\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Referers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  referer,\n  count(referer) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by referer\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  protocol,\n  count(protocol) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by protocol\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  country,\n  count(country) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp)\n  and\n  domain in ($domain)\ngroup by country\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status,\n  count(status) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by status\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  clientIP,\n  count(clientIP) as \"count\"\nFROM logs\nWHERE\n  $__timeFilter(timestamp) and\n  domain in ($domain)\ngroup by clientIP\nORDER BY timestamp"
    }
   ]
  }
 ]
}