version:                     '3'
services:
  mariadb:
    image:                   mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:   password
      MYSQL_DATABASE:        cloudflare
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ./mariadb:/var/lib/mysql

  api:
    build:                   src/
    restart:                 always
    command:                 npm start
    ports:
      - "9050:80"
