version:                     '3'
services:
  mariadb:
    image:                   mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:   password
      MYSQL_DATABASE:        cloudflare
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ./mariadb:/var/lib/mysql

  api:
    build:                   src/
    restart:                 always
    command:                 npm start
    ports:
      - "9050:80"
    volumes:
      - ./config.json:/app/config.json

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: always
    user: "$UID:$GID"
